#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace getDetail
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LKSDB")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPAZ_ENVANTERLİSTE(PAZ_ENVANTERLİSTE instance);
    partial void UpdatePAZ_ENVANTERLİSTE(PAZ_ENVANTERLİSTE instance);
    partial void DeletePAZ_ENVANTERLİSTE(PAZ_ENVANTERLİSTE instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::getDetail.Properties.Settings.Default.LKSDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CTN_SATICIBAZLIMALIYETKARZARAR> CTN_SATICIBAZLIMALIYETKARZARARs
		{
			get
			{
				return this.GetTable<CTN_SATICIBAZLIMALIYETKARZARAR>();
			}
		}
		
		public System.Data.Linq.Table<PAZ_ENVANTERLİSTE> PAZ_ENVANTERLİSTEs
		{
			get
			{
				return this.GetTable<PAZ_ENVANTERLİSTE>();
			}
		}
		
		public System.Data.Linq.Table<PAZ_DEPOBAZLISTOKFIYAT> PAZ_DEPOBAZLISTOKFIYATs
		{
			get
			{
				return this.GetTable<PAZ_DEPOBAZLISTOKFIYAT>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTN_SATICIBAZLIMALIYETKARZARAR")]
	public partial class CTN_SATICIBAZLIMALIYETKARZARAR
	{
		
		private System.Nullable<System.DateTime> _Tarih;
		
		private System.Nullable<int> _Ay;
		
		private string _FisNo;
		
		private string _SatisElemani;
		
		private string _FaturaTuru;
		
		private string _CariKodu;
		
		private string _CariAdi;
		
		private string _SatirTuru;
		
		private string _MalHizmetKodu;
		
		private string _MalHizmetAdi;
		
		private string _Aciklama;
		
		private string _DEPO;
		
		private System.Nullable<double> _Miktar;
		
		private System.Nullable<double> _KdvMatrah;
		
		private System.Nullable<double> _KdvTutar;
		
		private System.Nullable<double> _NetTutar;
		
		private string _Birim;
		
		private string _BOLGE;
		
		private System.Nullable<double> _BirimMaliyet;
		
		private System.Nullable<double> _GirisMaliyet;
		
		private System.Nullable<double> _KarZarar;
		
		public CTN_SATICIBAZLIMALIYETKARZARAR()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarih", DbType="Date")]
		public System.Nullable<System.DateTime> Tarih
		{
			get
			{
				return this._Tarih;
			}
			set
			{
				if ((this._Tarih != value))
				{
					this._Tarih = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ay", DbType="Int")]
		public System.Nullable<int> Ay
		{
			get
			{
				return this._Ay;
			}
			set
			{
				if ((this._Ay != value))
				{
					this._Ay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FisNo", DbType="VarChar(17)")]
		public string FisNo
		{
			get
			{
				return this._FisNo;
			}
			set
			{
				if ((this._FisNo != value))
				{
					this._FisNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SatisElemani", DbType="VarChar(51) NOT NULL", CanBeNull=false)]
		public string SatisElemani
		{
			get
			{
				return this._SatisElemani;
			}
			set
			{
				if ((this._SatisElemani != value))
				{
					this._SatisElemani = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaturaTuru", DbType="VarChar(29) NOT NULL", CanBeNull=false)]
		public string FaturaTuru
		{
			get
			{
				return this._FaturaTuru;
			}
			set
			{
				if ((this._FaturaTuru != value))
				{
					this._FaturaTuru = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CariKodu", DbType="VarChar(17)")]
		public string CariKodu
		{
			get
			{
				return this._CariKodu;
			}
			set
			{
				if ((this._CariKodu != value))
				{
					this._CariKodu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CariAdi", DbType="VarChar(201)")]
		public string CariAdi
		{
			get
			{
				return this._CariAdi;
			}
			set
			{
				if ((this._CariAdi != value))
				{
					this._CariAdi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SatirTuru", DbType="VarChar(7) NOT NULL", CanBeNull=false)]
		public string SatirTuru
		{
			get
			{
				return this._SatirTuru;
			}
			set
			{
				if ((this._SatirTuru != value))
				{
					this._SatirTuru = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MalHizmetKodu", DbType="VarChar(25)")]
		public string MalHizmetKodu
		{
			get
			{
				return this._MalHizmetKodu;
			}
			set
			{
				if ((this._MalHizmetKodu != value))
				{
					this._MalHizmetKodu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MalHizmetAdi", DbType="VarChar(51)")]
		public string MalHizmetAdi
		{
			get
			{
				return this._MalHizmetAdi;
			}
			set
			{
				if ((this._MalHizmetAdi != value))
				{
					this._MalHizmetAdi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aciklama", DbType="VarChar(251)")]
		public string Aciklama
		{
			get
			{
				return this._Aciklama;
			}
			set
			{
				if ((this._Aciklama != value))
				{
					this._Aciklama = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPO", DbType="VarChar(16)")]
		public string DEPO
		{
			get
			{
				return this._DEPO;
			}
			set
			{
				if ((this._DEPO != value))
				{
					this._DEPO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Miktar", DbType="Float")]
		public System.Nullable<double> Miktar
		{
			get
			{
				return this._Miktar;
			}
			set
			{
				if ((this._Miktar != value))
				{
					this._Miktar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KdvMatrah", DbType="Float")]
		public System.Nullable<double> KdvMatrah
		{
			get
			{
				return this._KdvMatrah;
			}
			set
			{
				if ((this._KdvMatrah != value))
				{
					this._KdvMatrah = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KdvTutar", DbType="Float")]
		public System.Nullable<double> KdvTutar
		{
			get
			{
				return this._KdvTutar;
			}
			set
			{
				if ((this._KdvTutar != value))
				{
					this._KdvTutar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NetTutar", DbType="Float")]
		public System.Nullable<double> NetTutar
		{
			get
			{
				return this._NetTutar;
			}
			set
			{
				if ((this._NetTutar != value))
				{
					this._NetTutar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Birim", DbType="VarChar(11)")]
		public string Birim
		{
			get
			{
				return this._Birim;
			}
			set
			{
				if ((this._Birim != value))
				{
					this._Birim = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BOLGE", DbType="VarChar(11)")]
		public string BOLGE
		{
			get
			{
				return this._BOLGE;
			}
			set
			{
				if ((this._BOLGE != value))
				{
					this._BOLGE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BirimMaliyet", DbType="Float")]
		public System.Nullable<double> BirimMaliyet
		{
			get
			{
				return this._BirimMaliyet;
			}
			set
			{
				if ((this._BirimMaliyet != value))
				{
					this._BirimMaliyet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GirisMaliyet", DbType="Float")]
		public System.Nullable<double> GirisMaliyet
		{
			get
			{
				return this._GirisMaliyet;
			}
			set
			{
				if ((this._GirisMaliyet != value))
				{
					this._GirisMaliyet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KarZarar", DbType="Float")]
		public System.Nullable<double> KarZarar
		{
			get
			{
				return this._KarZarar;
			}
			set
			{
				if ((this._KarZarar != value))
				{
					this._KarZarar = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PAZ_ENVANTERLİSTE")]
	public partial class PAZ_ENVANTERLİSTE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _envID;
		
		private string _envAdi;
		
		private string _envAnaGrup;
		
		private string _envMarka;
		
		private string _envModel;
		
		private string _envSeriNo;
		
		private System.Nullable<int> _envMiktar;
		
		private string _envKonum;
		
		private string _envSorumlu;
		
		private string _envDurum;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnenvIDChanging(int value);
    partial void OnenvIDChanged();
    partial void OnenvAdiChanging(string value);
    partial void OnenvAdiChanged();
    partial void OnenvAnaGrupChanging(string value);
    partial void OnenvAnaGrupChanged();
    partial void OnenvMarkaChanging(string value);
    partial void OnenvMarkaChanged();
    partial void OnenvModelChanging(string value);
    partial void OnenvModelChanged();
    partial void OnenvSeriNoChanging(string value);
    partial void OnenvSeriNoChanged();
    partial void OnenvMiktarChanging(System.Nullable<int> value);
    partial void OnenvMiktarChanged();
    partial void OnenvKonumChanging(string value);
    partial void OnenvKonumChanged();
    partial void OnenvSorumluChanging(string value);
    partial void OnenvSorumluChanged();
    partial void OnenvDurumChanging(string value);
    partial void OnenvDurumChanged();
    #endregion
		
		public PAZ_ENVANTERLİSTE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_envID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int envID
		{
			get
			{
				return this._envID;
			}
			set
			{
				if ((this._envID != value))
				{
					this.OnenvIDChanging(value);
					this.SendPropertyChanging();
					this._envID = value;
					this.SendPropertyChanged("envID");
					this.OnenvIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_envAdi", DbType="NVarChar(50)")]
		public string envAdi
		{
			get
			{
				return this._envAdi;
			}
			set
			{
				if ((this._envAdi != value))
				{
					this.OnenvAdiChanging(value);
					this.SendPropertyChanging();
					this._envAdi = value;
					this.SendPropertyChanged("envAdi");
					this.OnenvAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_envAnaGrup", DbType="NVarChar(50)")]
		public string envAnaGrup
		{
			get
			{
				return this._envAnaGrup;
			}
			set
			{
				if ((this._envAnaGrup != value))
				{
					this.OnenvAnaGrupChanging(value);
					this.SendPropertyChanging();
					this._envAnaGrup = value;
					this.SendPropertyChanged("envAnaGrup");
					this.OnenvAnaGrupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_envMarka", DbType="NVarChar(50)")]
		public string envMarka
		{
			get
			{
				return this._envMarka;
			}
			set
			{
				if ((this._envMarka != value))
				{
					this.OnenvMarkaChanging(value);
					this.SendPropertyChanging();
					this._envMarka = value;
					this.SendPropertyChanged("envMarka");
					this.OnenvMarkaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_envModel", DbType="NVarChar(50)")]
		public string envModel
		{
			get
			{
				return this._envModel;
			}
			set
			{
				if ((this._envModel != value))
				{
					this.OnenvModelChanging(value);
					this.SendPropertyChanging();
					this._envModel = value;
					this.SendPropertyChanged("envModel");
					this.OnenvModelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_envSeriNo", DbType="NVarChar(50)")]
		public string envSeriNo
		{
			get
			{
				return this._envSeriNo;
			}
			set
			{
				if ((this._envSeriNo != value))
				{
					this.OnenvSeriNoChanging(value);
					this.SendPropertyChanging();
					this._envSeriNo = value;
					this.SendPropertyChanged("envSeriNo");
					this.OnenvSeriNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_envMiktar", DbType="Int")]
		public System.Nullable<int> envMiktar
		{
			get
			{
				return this._envMiktar;
			}
			set
			{
				if ((this._envMiktar != value))
				{
					this.OnenvMiktarChanging(value);
					this.SendPropertyChanging();
					this._envMiktar = value;
					this.SendPropertyChanged("envMiktar");
					this.OnenvMiktarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_envKonum", DbType="NVarChar(50)")]
		public string envKonum
		{
			get
			{
				return this._envKonum;
			}
			set
			{
				if ((this._envKonum != value))
				{
					this.OnenvKonumChanging(value);
					this.SendPropertyChanging();
					this._envKonum = value;
					this.SendPropertyChanged("envKonum");
					this.OnenvKonumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_envSorumlu", DbType="NVarChar(50)")]
		public string envSorumlu
		{
			get
			{
				return this._envSorumlu;
			}
			set
			{
				if ((this._envSorumlu != value))
				{
					this.OnenvSorumluChanging(value);
					this.SendPropertyChanging();
					this._envSorumlu = value;
					this.SendPropertyChanged("envSorumlu");
					this.OnenvSorumluChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_envDurum", DbType="NVarChar(50)")]
		public string envDurum
		{
			get
			{
				return this._envDurum;
			}
			set
			{
				if ((this._envDurum != value))
				{
					this.OnenvDurumChanging(value);
					this.SendPropertyChanging();
					this._envDurum = value;
					this.SendPropertyChanged("envDurum");
					this.OnenvDurumChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PAZ_DEPOBAZLISTOKFIYAT")]
	public partial class PAZ_DEPOBAZLISTOKFIYAT
	{
		
		private string _CODE;
		
		private string _NAME;
		
		private string _BIRIM;
		
		private string _BARCODE;
		
		private System.Nullable<double> _ALISFIYATI;
		
		private System.Nullable<double> _SATISFIYATI;
		
		private System.Nullable<double> _GATEMSTOK;
		
		private System.Nullable<double> _KÜSGETSTOK;
		
		private System.Nullable<double> _İADESTOK;
		
		private System.Nullable<double> _TOPLAMSTOK;
		
		private System.Nullable<double> _GATEMTUTAR;
		
		private System.Nullable<double> _KÜSGETTUTAR;
		
		private System.Nullable<double> _GENELTUTAR;
		
		public PAZ_DEPOBAZLISTOKFIYAT()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODE", DbType="VarChar(25)")]
		public string CODE
		{
			get
			{
				return this._CODE;
			}
			set
			{
				if ((this._CODE != value))
				{
					this._CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(51)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIRIM", DbType="VarChar(11)")]
		public string BIRIM
		{
			get
			{
				return this._BIRIM;
			}
			set
			{
				if ((this._BIRIM != value))
				{
					this._BIRIM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BARCODE", DbType="VarChar(101)")]
		public string BARCODE
		{
			get
			{
				return this._BARCODE;
			}
			set
			{
				if ((this._BARCODE != value))
				{
					this._BARCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALISFIYATI", DbType="Float")]
		public System.Nullable<double> ALISFIYATI
		{
			get
			{
				return this._ALISFIYATI;
			}
			set
			{
				if ((this._ALISFIYATI != value))
				{
					this._ALISFIYATI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SATISFIYATI", DbType="Float")]
		public System.Nullable<double> SATISFIYATI
		{
			get
			{
				return this._SATISFIYATI;
			}
			set
			{
				if ((this._SATISFIYATI != value))
				{
					this._SATISFIYATI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GATEMSTOK", DbType="Float")]
		public System.Nullable<double> GATEMSTOK
		{
			get
			{
				return this._GATEMSTOK;
			}
			set
			{
				if ((this._GATEMSTOK != value))
				{
					this._GATEMSTOK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KÜSGETSTOK", DbType="Float")]
		public System.Nullable<double> KÜSGETSTOK
		{
			get
			{
				return this._KÜSGETSTOK;
			}
			set
			{
				if ((this._KÜSGETSTOK != value))
				{
					this._KÜSGETSTOK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_İADESTOK", DbType="Float")]
		public System.Nullable<double> İADESTOK
		{
			get
			{
				return this._İADESTOK;
			}
			set
			{
				if ((this._İADESTOK != value))
				{
					this._İADESTOK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOPLAMSTOK", DbType="Float")]
		public System.Nullable<double> TOPLAMSTOK
		{
			get
			{
				return this._TOPLAMSTOK;
			}
			set
			{
				if ((this._TOPLAMSTOK != value))
				{
					this._TOPLAMSTOK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GATEMTUTAR", DbType="Float")]
		public System.Nullable<double> GATEMTUTAR
		{
			get
			{
				return this._GATEMTUTAR;
			}
			set
			{
				if ((this._GATEMTUTAR != value))
				{
					this._GATEMTUTAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KÜSGETTUTAR", DbType="Float")]
		public System.Nullable<double> KÜSGETTUTAR
		{
			get
			{
				return this._KÜSGETTUTAR;
			}
			set
			{
				if ((this._KÜSGETTUTAR != value))
				{
					this._KÜSGETTUTAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GENELTUTAR", DbType="Float")]
		public System.Nullable<double> GENELTUTAR
		{
			get
			{
				return this._GENELTUTAR;
			}
			set
			{
				if ((this._GENELTUTAR != value))
				{
					this._GENELTUTAR = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
